version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - firebase

  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    ports:
      - "4000:4000"  # Emulator UI
      - "9099:9099"  # Auth
      - "8080:8080"  # Firestore
      - "9199:9199"  # Storage
      - "4400:4400"  # Hub
      - "4500:4500"  # Reserved
      - "9150:9150"  # Reserved
    volumes:
      - .:/app