FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache openjdk11-jre-headless

RUN npm install -g firebase-tools

COPY firebase.json .
COPY .firebaserc .

EXPOSE 4000 9099 8080 9199

CMD ["firebase", "emulators:start", "--project", "tecnexecommerce"]